### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by mcandre** [vilmacio/depixelate#5]
When I try to import the module, I get an error.

```console
$ python
>>> import depixelate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/.asdf/installs/python/3.10.7/lib/python3.10/site-packages/depixelate.py", line 5, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by vilmacio** [comment]
Make sure you are using v1.0.6 now
