### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by shiva17** [vilmacio/depixelate#7]
Traceback (most recent call last):
  File "C:\M-Tech\projects\mtech\lib\site-packages\PIL\Image.py", line 3231, in open
    fp.seek(0)
AttributeError: 'numpy.ndarray' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\M-Tech\projects\ESRGAN\deblur.py", line 6, in <module>
    result = depixelate.apply(original_image, 7, 600)
  File "C:\M-Tech\projects\mtech\lib\site-packages\depixelate.py", line 10, in apply
    pil_image = Image.open(image).convert('RGBA')
  File "C:\M-Tech\projects\mtech\lib\site-packages\PIL\Image.py", line 3233, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'numpy.ndarray' object has no attribute 'read'. Did you mean: 'real'?

**Comment by vilmacio** [comment]
Hey man! Thanks for your time and sorry for the huge delay!

A fix was commited to the branch created for that issue. It would be amazing if you could take a time to test it and check if it's resolved in your case.

**Comment by jrziehn** [comment]
Thank you for the update (and the package) - I can confirm that this solved the issue at least for me.
